package com.pickleball.booking.lessonrequest.infrastructure;

import com.pickleball.booking.lessonrequest.domain.LessonRequestStatus;
import com.pickleball.booking.shared.application.BusinessException;
import jakarta.persistence.*;
import java.time.Instant; import java.util.UUID;

@Entity @Table(name="lesson_requests")
public class LessonRequestEntity {
    @Id private UUID id; @Column(name="organization_id",nullable=false) private UUID organizationId; @Column(name="requester_user_id",nullable=false) private UUID requesterUserId; @Column(name="preferred_coach_profile_id") private UUID preferredCoachProfileId; @Column(name="selected_availability_proposal_id") private UUID selectedAvailabilityProposalId;
    @Column(name="lesson_type",nullable=false) private String lessonType; @Column(name="schedule_type",nullable=false) private String scheduleType; @Column(name="billing_mode",nullable=false) private String billingMode; @Column(name="skill_level") private String skillLevel;
    @Column(name="participant_count",nullable=false) private short participantCount; @Column(name="guest_participant_count",nullable=false) private short guestParticipantCount; @Column(name="minimum_participants") private Short minimumParticipants; @Column(name="maximum_participants") private Short maximumParticipants; @Column(name="requested_session_count",nullable=false) private short requestedSessionCount;
    @Enumerated(EnumType.STRING) @Column(nullable=false) private LessonRequestStatus status=LessonRequestStatus.DRAFT; private String notes; @Column(name="submitted_at") private Instant submittedAt; @Column(name="reviewed_by") private UUID reviewedBy; @Column(name="reviewed_at") private Instant reviewedAt; @Column(name="review_note") private String reviewNote; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Version private long version;
    protected LessonRequestEntity() { }
    public LessonRequestEntity(UUID org, UUID requester, UUID coach, UUID selectedAvailability, String lessonType, String scheduleType, String billingMode, String skill, short participants, short guests, Short min, Short max, short sessions, String notes) { id=UUID.randomUUID(); organizationId=org;requesterUserId=requester;preferredCoachProfileId=coach;selectedAvailabilityProposalId=selectedAvailability;this.lessonType=lessonType;this.scheduleType=scheduleType;this.billingMode=billingMode;skillLevel=skill;participantCount=participants;guestParticipantCount=guests;minimumParticipants=min;maximumParticipants=max;requestedSessionCount=sessions;this.notes=notes; validate(); }
    @PrePersist void created(){var now=Instant.now();createdAt=now;updatedAt=now;} @PreUpdate void updated(){updatedAt=Instant.now();}
    public UUID getId(){return id;} public UUID getOrganizationId(){return organizationId;} public UUID getRequesterUserId(){return requesterUserId;} public UUID getPreferredCoachProfileId(){return preferredCoachProfileId;} public UUID getSelectedAvailabilityProposalId(){return selectedAvailabilityProposalId;} public LessonRequestStatus getStatus(){return status;} public String getLessonType(){return lessonType;} public String getScheduleType(){return scheduleType;} public String getBillingMode(){return billingMode;} public String getSkillLevel(){return skillLevel;} public short getParticipantCount(){return participantCount;} public short getGuestParticipantCount(){return guestParticipantCount;} public Short getMinimumParticipants(){return minimumParticipants;} public Short getMaximumParticipants(){return maximumParticipants;} public short getRequestedSessionCount(){return requestedSessionCount;} public String getNotes(){return notes;} public Instant getSubmittedAt(){return submittedAt;} public UUID getReviewedBy(){return reviewedBy;} public Instant getReviewedAt(){return reviewedAt;} public String getReviewNote(){return reviewNote;}
    public void selectAvailability(UUID availabilityProposalId) { if(status!=LessonRequestStatus.DRAFT) throw new BusinessException("STATE_TRANSITION_INVALID","Availability selection can only change on a draft"); selectedAvailabilityProposalId=availabilityProposalId; }
    public void submit(){if(status!=LessonRequestStatus.DRAFT) throw new BusinessException("STATE_TRANSITION_INVALID","Only a draft request can be submitted"); status=LessonRequestStatus.SUBMITTED;submittedAt=Instant.now();}
    public void review(boolean approve, UUID actor, String note){if(status!=LessonRequestStatus.SUBMITTED) throw new BusinessException("STATE_TRANSITION_INVALID","Only a submitted request can be reviewed");if(note==null||note.isBlank())throw new BusinessException("VALIDATION_FAILED","Review note is required");status=approve?LessonRequestStatus.APPROVED:LessonRequestStatus.REJECTED;reviewedBy=actor;reviewedAt=Instant.now();reviewNote=note.trim();}
    private void validate(){if(participantCount<=0||requestedSessionCount<=0) throw new BusinessException("VALIDATION_FAILED","Participant and session counts must be positive");if(!"PRIVATE".equals(lessonType)&&!"GROUP".equals(lessonType))throw new BusinessException("VALIDATION_FAILED","Invalid lesson type");if(!"SINGLE".equals(scheduleType)&&!"RECURRING".equals(scheduleType))throw new BusinessException("VALIDATION_FAILED","Invalid schedule type");if(!"FULL_COURSE".equals(billingMode)&&!"PER_SESSION".equals(billingMode))throw new BusinessException("VALIDATION_FAILED","Invalid billing mode");if("SINGLE".equals(scheduleType)&&requestedSessionCount!=1)throw new BusinessException("VALIDATION_FAILED","Single requests need one session");if("PRIVATE".equals(lessonType)&&maximumParticipants!=null&&maximumParticipants>4)throw new BusinessException("VALIDATION_FAILED","Private requests allow at most four participants");if("GROUP".equals(lessonType)&&(minimumParticipants==null||maximumParticipants==null||minimumParticipants>maximumParticipants))throw new BusinessException("VALIDATION_FAILED","Group participant range is invalid");}
}
