package com.pickleball.booking.coach.api;

import com.pickleball.booking.coach.application.CoachService; import com.pickleball.booking.coach.infrastructure.*; import com.pickleball.booking.identity.application.AuthenticatedPrincipal; import com.pickleball.booking.shared.api.ApiResponse;
import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.Instant; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1")
public class CoachController {
 private final CoachService service; public CoachController(CoachService service){this.service=service;} private AuthenticatedPrincipal p(Authentication a){return (AuthenticatedPrincipal)a.getPrincipal();} private <T> ApiResponse<T> ok(T data,HttpServletRequest r){return ApiResponse.of(data,(String)r.getAttribute("requestId"));}
 @PostMapping("/coach-applications") @ResponseStatus(HttpStatus.CREATED) public ApiResponse<ApplicationView> apply(Authentication a,@Valid @RequestBody ApplyRequest r,HttpServletRequest h){return ok(application(service.apply(p(a),r.applicationNote(),r.skillLevel(),r.bio())),h);}
 @GetMapping("/coach-applications/mine") public ApiResponse<List<ApplicationView>> mine(Authentication a,HttpServletRequest h){return ok(service.myApplications(p(a)).stream().map(this::application).toList(),h);}
 @GetMapping("/coach-applications") public ApiResponse<List<ApplicationView>> reviewList(Authentication a,@RequestParam UUID organizationId,HttpServletRequest h){return ok(service.applicationsForReview(p(a),organizationId).stream().map(this::application).toList(),h);}
 @PostMapping("/coach-applications/{id}/review") public ApiResponse<ApplicationView> review(Authentication a,@PathVariable UUID id,@Valid @RequestBody ReviewRequest r,HttpServletRequest h){return ok(application(service.reviewApplication(p(a),id,"APPROVE".equals(r.decision()),r.reviewNote())),h);}
 @PostMapping("/coach-availability-proposals") @ResponseStatus(HttpStatus.CREATED) public ApiResponse<AvailabilityView> create(Authentication a,@Valid @RequestBody AvailabilityRequest r,HttpServletRequest h){return ok(proposal(service.createAvailability(p(a),r.startAt(),r.endAt(),r.preferredVenueId())),h);}
 @PatchMapping("/coach-availability-proposals/{id}") public ApiResponse<AvailabilityView> update(Authentication a,@PathVariable UUID id,@Valid @RequestBody AvailabilityRequest r,HttpServletRequest h){return ok(proposal(service.updateAvailability(p(a),id,r.startAt(),r.endAt(),r.preferredVenueId())),h);}
 @PostMapping("/coach-availability-proposals/{id}/submission") public ApiResponse<AvailabilityView> submit(Authentication a,@PathVariable UUID id,HttpServletRequest h){return ok(proposal(service.submitAvailability(p(a),id)),h);}
 @PostMapping("/coach-availability-proposals/{id}/review") public ApiResponse<AvailabilityView> reviewAvailability(Authentication a,@PathVariable UUID id,@Valid @RequestBody ReviewRequest r,HttpServletRequest h){return ok(proposal(service.reviewAvailability(p(a),id,"APPROVE".equals(r.decision()),r.reviewNote())),h);}
 @PostMapping("/coach-availability-proposals/{id}/close") public ApiResponse<AvailabilityView> close(Authentication a,@PathVariable UUID id,HttpServletRequest h){return ok(proposal(service.closeAvailability(p(a),id)),h);}
 @GetMapping("/coach-availability-proposals/mine") public ApiResponse<List<AvailabilityView>> myAvailability(Authentication a,HttpServletRequest h){return ok(service.myAvailability(p(a)).stream().map(this::proposal).toList(),h);}
 @GetMapping("/coach-availability-proposals/available") public ApiResponse<List<AvailabilityView>> approvedAvailability(Authentication a,HttpServletRequest h){return ok(service.approvedAvailability(p(a)).stream().map(this::proposal).toList(),h);}
 @GetMapping("/coach-availability-proposals") public ApiResponse<List<AvailabilityView>> availabilityReviewList(Authentication a,@RequestParam UUID organizationId,HttpServletRequest h){return ok(service.availabilityForReview(p(a),organizationId).stream().map(this::proposal).toList(),h);}
 private ApplicationView application(CoachApplicationEntity e){return new ApplicationView(e.getId(),e.getCoachProfileId(),e.getStatus().name(),e.getApplicationNote(),e.getSubmittedAt(),e.getReviewedBy(),e.getReviewedAt(),e.getReviewNote());} private AvailabilityView proposal(AvailabilityProposalEntity e){return new AvailabilityView(e.getId(),e.getCoachProfileId(),e.getStartAt(),e.getEndAt(),e.getPreferredVenueId(),e.getStatus().name(),e.getSubmittedAt(),e.getReviewedBy(),e.getReviewedAt(),e.getReviewNote());}
 public record ApplyRequest(@Size(max=5000) String applicationNote,@Size(max=30) String skillLevel,@Size(max=10000) String bio){} public record ReviewRequest(@Pattern(regexp="APPROVE|REJECT") String decision,@NotBlank @Size(max=5000) String reviewNote){} public record AvailabilityRequest(@NotNull Instant startAt,@NotNull Instant endAt,UUID preferredVenueId){} public record ApplicationView(UUID id,UUID coachProfileId,String status,String applicationNote,Instant submittedAt,UUID reviewedBy,Instant reviewedAt,String reviewNote){} public record AvailabilityView(UUID id,UUID coachProfileId,Instant startAt,Instant endAt,UUID preferredVenueId,String status,Instant submittedAt,UUID reviewedBy,Instant reviewedAt,String reviewNote){}
}
