import {
  ApiClientError,
  createApiClient,
  type CoachCancellationReviewQueueItem,
  type CourseSessionSummary,
  type CourseSummary,
  type SessionChangeReviewQueueItem,
} from "@pickleball/api-client";
import { useEffect, useState } from "react";

const api = createApiClient({ baseUrl: import.meta.env.VITE_API_BASE_URL ?? "/api/v1" });
type ReviewDraft = { kind: "change" | "cancellation"; requestId: string; decision: "APPROVE" | "REJECT"; label: string };
type DirectDraft = { session: CourseSessionSummary; startAt: Date; endAt: Date; reason: string };

export function CourseOperationsWorkQueue({ token, organizationId }: { token: string; organizationId: string }) {
  const [courses, setCourses] = useState<CourseSummary[]>([]);
  const [sessions, setSessions] = useState<CourseSessionSummary[]>([]);
  const [selectedCourse, setSelectedCourse] = useState<CourseSummary | null>(null);
  const [changes, setChanges] = useState<SessionChangeReviewQueueItem[]>([]);
  const [cancellations, setCancellations] = useState<CoachCancellationReviewQueueItem[]>([]);
  const [review, setReview] = useState<ReviewDraft | null>(null);
  const [direct, setDirect] = useState<DirectDraft | null>(null);
  const [message, setMessage] = useState("");
  const refresh = async () => { const [courseRows, changeQueue, cancellationQueue] = await Promise.all([api.listCourses(token, { organizationId, size: 100, sort: "nextSessionAt,asc" }), api.sessionChangeRequestsForReview(token, organizationId), api.coachCancellationRequestsForReview(token, organizationId)]); setCourses(courseRows); setChanges(changeQueue); setCancellations(cancellationQueue); };
  useEffect(() => { void refresh().catch(() => setMessage("Unable to load Course Operations.")); }, [token, organizationId]);
  async function openCourse(course: CourseSummary) { try { setSelectedCourse(course); setSessions(await api.listCourseSessions(token, course.id)); setDirect(null); } catch { setMessage("Unable to load course sessions."); } }
  async function submitReview(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!review) return; const reason = String(new FormData(event.currentTarget).get("reason")); try { if (review.kind === "change") await api.reviewSessionChangeRequest(token, review.requestId, `admin-change-review-${review.requestId}-${review.decision}`, { decision: review.decision, reason }); else await api.reviewCoachSessionCancellation(token, review.requestId, { decision: review.decision, reason }); setMessage("Review saved and queues refreshed."); setReview(null); await refresh(); if (selectedCourse) await openCourse(selectedCourse); } catch (caught) { setMessage(commandError(caught, "Unable to save review.")); } }
  async function confirmDirectReschedule() { if (!direct) return; try { await api.rescheduleCourseSession(token, direct.session.id, `admin-direct-reschedule-${direct.session.id}-${direct.startAt.toISOString()}`, direct.startAt, direct.endAt, direct.reason); setMessage("Session rescheduled; reservations were shifted atomically."); setDirect(null); await refresh(); if (selectedCourse) await openCourse(selectedCourse); } catch (caught) { setMessage(commandError(caught, "Unable to reschedule session.")); } }
  return <section aria-label="Course operations"><h2>Course operations</h2>{message && <p role="status">{message}</p>}<h3>Pending reschedule requests</h3>{changes.length === 0 ? <p>No pending reschedule requests.</p> : <ul>{changes.map((item) => <li key={item.requestId}><strong>{item.courseNo} · session {item.sequenceNo}</strong> · {item.requesterDisplayName}<br />Current: {formatDate(item.scheduledStartAt)}<br />Proposed: {formatDate(item.proposedStartAt)}<br />Reason: {item.reason}<ReviewButtons onChoose={(decision) => setReview({ kind: "change", requestId: item.requestId, decision, label: `${item.courseNo} session ${item.sequenceNo} reschedule` })} /></li>)}</ul>}<h3>Pending coach cancellations</h3>{cancellations.length === 0 ? <p>No pending coach cancellation requests.</p> : <ul>{cancellations.map((item) => <li key={item.requestId}><strong>{item.courseNo} · session {item.sequenceNo}</strong> · {item.requesterDisplayName} · {formatDate(item.scheduledStartAt)}<br />Reason: {item.reason}<ReviewButtons onChoose={(decision) => setReview({ kind: "cancellation", requestId: item.requestId, decision, label: `${item.courseNo} session ${item.sequenceNo} coach cancellation` })} /></li>)}</ul>}<h3>Formal courses</h3>{courses.length === 0 ? <p>No formal courses yet.</p> : <ul>{courses.map((course) => <li key={course.id}><button onClick={() => void openCourse(course)}>Open course</button> {course.courseNo} · {course.status} · next {course.nextSessionStartAt ? formatDate(course.nextSessionStartAt) : "none"}</li>)}</ul>}{selectedCourse && <section aria-label="Formal course sessions"><h3>{selectedCourse.courseNo}</h3><ul>{sessions.map((session) => <li key={session.id}>Session {session.sequenceNo} · {formatDate(session.scheduledStartAt)} ～ {formatDate(session.scheduledEndAt)} · {session.status} · {session.coachDisplayName ?? "Coach pending"} · {session.venueName ?? "Venue pending"}{["SCHEDULED", "POSTPONED"].includes(session.status) && <DirectRescheduleForm session={session} onPrepare={setDirect} />}</li>)}</ul><button onClick={() => { setSelectedCourse(null); setSessions([]); setDirect(null); }}>Close course</button></section>}{review && <section role="dialog" aria-label="Confirm Course Operations review"><h3>{review.decision === "APPROVE" ? "Approve request" : "Reject request"}</h3><p>{review.label}</p><form onSubmit={submitReview}><label>Decision reason<textarea name="reason" required maxLength={5000} /></label><button>Confirm review</button><button type="button" onClick={() => setReview(null)}>Cancel</button></form></section>}{direct && <section role="dialog" aria-label="Confirm direct reschedule"><h3>Confirm direct reschedule</h3><p>Session {direct.session.sequenceNo}: {formatDate(direct.session.scheduledStartAt)} → {formatDate(direct.startAt)}</p><p>{direct.reason}</p><button onClick={() => void confirmDirectReschedule()}>Confirm reschedule</button><button onClick={() => setDirect(null)}>Cancel</button></section>}</section>;
}
function DirectRescheduleForm({ session, onPrepare }: { session: CourseSessionSummary; onPrepare: (draft: DirectDraft) => void }) { return <form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const startAt = new Date(String(data.get("startAt"))); const endAt = new Date(String(data.get("endAt"))); const reason = String(data.get("reason")); if (!Number.isFinite(startAt.getTime()) || !Number.isFinite(endAt.getTime()) || startAt >= endAt) return; onPrepare({ session, startAt, endAt, reason }); }}><label>New start<input name="startAt" type="datetime-local" required /></label><label>New end<input name="endAt" type="datetime-local" required /></label><label>Reason<input name="reason" required maxLength={5000} /></label><button>Direct reschedule</button></form>; }
function ReviewButtons({ onChoose }: { onChoose: (decision: "APPROVE" | "REJECT") => void }) { return <><button onClick={() => onChoose("APPROVE")}>Approve</button><button onClick={() => onChoose("REJECT")}>Reject</button></>; }
function formatDate(value: Date) { return value.toLocaleString("zh-TW", { timeZone: "Asia/Taipei" }); }
function commandError(caught: unknown, fallback: string) { return caught instanceof ApiClientError ? `${fallback} ${caught.code}` : fallback; }
