import { cloneElement, useEffect, useId, useRef, type ButtonHTMLAttributes, type HTMLAttributes, type PropsWithChildren, type ReactElement, type ReactNode } from "react";

export function PageShell({ children }: PropsWithChildren) { return <main className="ui-page-shell">{children}</main>; }
export function PageHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) { return <header className="ui-page-header"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="ui-page-header__actions">{actions}</div>}</header>; }
export function Card({ children, className = "", ...props }: PropsWithChildren<HTMLAttributes<HTMLElement>>) { return <section className={`ui-card ${className}`.trim()} {...props}>{children}</section>; }
type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "danger"; loading?: boolean };
export function Button({ variant = "primary", loading = false, children, disabled, className = "", ...props }: ButtonProps) { return <button className={`ui-button ui-button--${variant} ${className}`.trim()} disabled={disabled || loading} aria-busy={loading || undefined} {...props}>{loading ? "處理中…" : children}</button>; }
type FieldControlProps = { id?: string; "aria-describedby"?: string; "aria-invalid"?: boolean };
export function FormField({ label, hint, error, required, children }: { label: string; hint?: string; error?: string; required?: boolean; children: ReactElement<FieldControlProps> }) { const id = useId(); const helpId = hint || error ? `${id}-help` : undefined; return <div className="ui-field"><label htmlFor={id}>{label}{required && <span aria-hidden="true">（必填）</span>}</label>{cloneElement(children, { id: children.props.id ?? id, "aria-describedby": children.props["aria-describedby"] ?? helpId, "aria-invalid": Boolean(error) || children.props["aria-invalid"] })}{(hint || error) && <p id={helpId} className={error ? "ui-field__error" : "ui-field__hint"}>{error || hint}</p>}</div>; }
export function StatusBadge({ tone = "neutral", children }: PropsWithChildren<{ tone?: "success" | "warning" | "danger" | "neutral" }>) { return <span className={`ui-status ui-status--${tone}`}>{children}</span>; }
export function Alert({ tone = "info", children }: PropsWithChildren<{ tone?: "info" | "success" | "warning" | "danger" }>) { return <div className={`ui-alert ui-alert--${tone}`} role={tone === "danger" ? "alert" : "status"}>{children}</div>; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <section className="ui-empty-state"><h2>{title}</h2>{description && <p>{description}</p>}{action}</section>; }
export function Skeleton({ lines = 3, label = "載入中" }: { lines?: number; label?: string }) { return <div className="ui-skeleton" role="status" aria-label={label}>{Array.from({ length: lines }, (_, index) => <span key={index} />)}</div>; }
export function ConfirmationDialog({ open, title, description, confirmLabel = "確認", cancelLabel = "取消", danger = false, onConfirm, onCancel }: { open: boolean; title: string; description: ReactNode; confirmLabel?: string; cancelLabel?: string; danger?: boolean; onConfirm: () => void; onCancel: () => void }) { const dialogRef = useRef<HTMLDialogElement>(null); const confirmRef = useRef<HTMLButtonElement>(null); const returnFocusRef = useRef<HTMLElement | null>(null); const titleId = useId(); useEffect(() => { const dialog = dialogRef.current; if (!dialog) return; if (open) { returnFocusRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; if (!dialog.open) dialog.showModal?.(); confirmRef.current?.focus(); } else if (dialog.open) dialog.close(); }, [open]); function close() { onCancel(); queueMicrotask(() => returnFocusRef.current?.focus()); } return <dialog ref={dialogRef} className="ui-dialog" aria-labelledby={titleId} onCancel={(event) => { event.preventDefault(); close(); }} onClick={(event) => { if (event.target === event.currentTarget) close(); }}><div className="ui-dialog__content"><h2 id={titleId}>{title}</h2><div>{description}</div><div className="ui-dialog__actions"><Button variant="secondary" onClick={close}>{cancelLabel}</Button><button ref={confirmRef} className={`ui-button ui-button--${danger ? "danger" : "primary"}`} onClick={onConfirm}>{confirmLabel}</button></div></div></dialog>; }
