package com.pickleball.booking.lessonrequest.application;

import com.pickleball.booking.coach.domain.CoachProfileApprovalStatus;
import com.pickleball.booking.coach.infrastructure.CoachProfileRepository;
import com.pickleball.booking.coach.infrastructure.AvailabilityProposalRepository;
import com.pickleball.booking.coach.domain.AvailabilityProposalStatus;
import com.pickleball.booking.identity.application.*;
import com.pickleball.booking.identity.domain.*;
import com.pickleball.booking.identity.infrastructure.RoleAssignmentRepository;
import com.pickleball.booking.lessonrequest.infrastructure.*;
import com.pickleball.booking.shared.application.*;
import jakarta.transaction.Transactional;
import java.time.Instant; import java.util.*;
import org.springframework.stereotype.Service; import org.springframework.jdbc.core.JdbcTemplate;

@Service
public class LessonRequestService {
 private final IdentityService identity; private final OrganizationScopeResolver scopes; private final CoachProfileRepository profiles; private final AvailabilityProposalRepository availability; private final RoleAssignmentRepository roles; private final LessonRequestRepository requests; private final LessonSessionPreferenceRepository preferences; private final IdempotencyService idempotency; private final AuditOutboxService audit; private final JdbcTemplate jdbc;
 public LessonRequestService(IdentityService identity,OrganizationScopeResolver scopes,CoachProfileRepository profiles,AvailabilityProposalRepository availability,RoleAssignmentRepository roles,LessonRequestRepository requests,LessonSessionPreferenceRepository preferences,IdempotencyService idempotency,AuditOutboxService audit,JdbcTemplate jdbc){this.identity=identity;this.scopes=scopes;this.profiles=profiles;this.availability=availability;this.roles=roles;this.requests=requests;this.preferences=preferences;this.idempotency=idempotency;this.audit=audit;this.jdbc=jdbc;}
 @Transactional public LessonRequestEntity create(AuthenticatedPrincipal actor, CreateCommand command){identity.requireActiveUser(actor.userId());UUID org=scopes.activeOrganizationFor(actor.userId(),RoleCode.STUDENT);validateSelection(org,command.preferredCoachProfileId(),command.selectedAvailabilityProposalId());if(command.preferredCoachProfileId()!=null){var coach=profiles.findById(command.preferredCoachProfileId()).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Preferred coach was not found"));if(!coach.getOrganizationId().equals(org)||coach.getApprovalStatus()!=CoachProfileApprovalStatus.APPROVED)throw new BusinessException("COACH_NOT_APPROVED","Preferred coach is not eligible");}
   var request=requests.save(new LessonRequestEntity(org,actor.userId(),command.preferredCoachProfileId(),command.selectedAvailabilityProposalId(),command.lessonType(),command.scheduleType(),command.billingMode(),command.skillLevel(),command.participantCount(),command.guestParticipantCount(),command.minimumParticipants(),command.maximumParticipants(),command.requestedSessionCount(),command.notes()));
   if(command.sessionPreferences()==null||command.sessionPreferences().isEmpty())throw new BusinessException("VALIDATION_FAILED","At least one session preference is required");for(var p:command.sessionPreferences()){if(!p.startAt().isAfter(Instant.now()))throw new BusinessException("BOOKING_TIME_NOT_FUTURE","Session preference must be in the future");preferences.save(new LessonSessionPreferenceEntity(request.getId(),p.sequenceNo(),p.startAt(),p.endAt(),p.preferredVenueId(),p.note()));}return request; }
 @Transactional public LessonRequestEntity updateSelection(AuthenticatedPrincipal actor,UUID id,UUID selection){var request=owned(actor,id);validateSelection(request.getOrganizationId(),request.getPreferredCoachProfileId(),selection);request.selectAvailability(selection);return request;}
 @Transactional public LessonRequestEntity submit(AuthenticatedPrincipal actor,UUID id,String idempotencyKey){var request=owned(actor,id);var record=idempotency.begin(request.getOrganizationId(),actor.userId(),"LESSON_REQUEST_SUBMISSION",idempotencyKey,id.toString());if(record.getResultResourceId()!=null)return requests.findById(record.getResultResourceId()).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Idempotent submission result was not found"));if(request.getSelectedAvailabilityProposalId()!=null){var proposal=availability.findLockedById(request.getSelectedAvailabilityProposalId()).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Selected availability was not found"));validateSelectedForSubmit(request,proposal);request.submit();UUID claimId=UUID.randomUUID();if(jdbc.update("insert into coach_availability_claims (id, organization_id, coach_availability_proposal_id, lesson_request_id, status) values (?, ?, ?, ?, 'ACTIVE') on conflict (coach_availability_proposal_id) where status = 'ACTIVE' do nothing",claimId,request.getOrganizationId(),proposal.getId(),request.getId())!=1)throw new BusinessException("AVAILABILITY_ALREADY_CLAIMED","This availability has already been claimed");audit.record(request.getOrganizationId(),actor.userId(),"AVAILABILITY_CLAIM_ACQUIRED","AvailabilityClaim",claimId,null);}else request.submit();audit.record(request.getOrganizationId(),actor.userId(),"LESSON_REQUEST_SUBMITTED","LessonRequest",request.getId(),null);record.complete("LessonRequest",request.getId(),200);return request;}
 @Transactional public LessonRequestEntity review(AuthenticatedPrincipal actor,UUID id,boolean approve,String note){var request=requests.findLockedById(id).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Lesson request was not found"));requireCommittee(actor,request.getOrganizationId());request.review(approve,actor.userId(),note);audit.record(request.getOrganizationId(),actor.userId(),approve?"LESSON_REQUEST_APPROVED":"LESSON_REQUEST_REJECTED","LessonRequest",request.getId(),note);return request;}
 @Transactional public LessonRequestEntity detail(AuthenticatedPrincipal actor,UUID id){var request=requests.findById(id).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Lesson request was not found"));if(request.getRequesterUserId().equals(actor.userId())){identity.requireActiveUser(actor.userId());return request;}requireCommittee(actor,request.getOrganizationId());return request;}
 @Transactional public List<LessonRequestEntity> mine(AuthenticatedPrincipal actor){identity.requireActiveUser(actor.userId());return requests.findByRequesterUserIdOrderByCreatedAtDesc(actor.userId());}
 @Transactional public List<LessonRequestEntity> forReview(AuthenticatedPrincipal actor,UUID org){requireCommittee(actor,org);return requests.findByOrganizationIdOrderByCreatedAtDesc(org);}
 @Transactional public List<LessonSessionPreferenceEntity> preferences(UUID requestId){return preferences.findByLessonRequestIdOrderBySequenceNo(requestId);}
 private LessonRequestEntity owned(AuthenticatedPrincipal actor,UUID id){var request=requests.findLockedById(id).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Lesson request was not found"));identity.requireActiveUser(actor.userId());if(!request.getRequesterUserId().equals(actor.userId()))throw new BusinessException("ORG_SCOPE_DENIED","Lesson request is outside your scope");return request;}
 private void requireCommittee(AuthenticatedPrincipal actor,UUID org){identity.requireActiveUser(actor.userId());if(!identity.isAuthorizedForOrganization(actor,RoleCode.COMMITTEE,org))throw new BusinessException("AUTH_FORBIDDEN","Committee role is required for this organization");}
 private void validateSelection(UUID org,UUID preferredCoachId,UUID selectedAvailabilityId){if(selectedAvailabilityId==null)return;var proposal=availability.findById(selectedAvailabilityId).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Selected availability was not found"));if(!proposal.getOrganizationId().equals(org))throw new BusinessException("ORG_SCOPE_DENIED","Selected availability is outside the organization");if(proposal.getStatus()!=AvailabilityProposalStatus.APPROVED)throw new BusinessException("AVAILABILITY_NOT_APPROVED","Selected availability is not approved");if(preferredCoachId==null||!preferredCoachId.equals(proposal.getCoachProfileId()))throw new BusinessException("VALIDATION_FAILED","Preferred coach must match selected availability");var profile=profiles.findById(proposal.getCoachProfileId()).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Availability coach was not found"));if(profile.getApprovalStatus()!=CoachProfileApprovalStatus.APPROVED)throw new BusinessException("COACH_NOT_APPROVED","Availability coach is not approved");}
 private void validateSelectedForSubmit(LessonRequestEntity request,com.pickleball.booking.coach.infrastructure.AvailabilityProposalEntity proposal){validateSelection(request.getOrganizationId(),request.getPreferredCoachProfileId(),proposal.getId());if(!proposal.getStartAt().isAfter(Instant.now()))throw new BusinessException("BOOKING_TIME_NOT_FUTURE","Selected availability is no longer in the future");var profile=profiles.findById(proposal.getCoachProfileId()).orElseThrow(()->new BusinessException("RESOURCE_NOT_FOUND","Availability coach was not found"));if(!roles.existsByUserIdAndOrganizationIdAndRoleCodeAndStatus(profile.getUserId(),request.getOrganizationId(),RoleCode.COACH,RoleAssignmentStatus.ACTIVE))throw new BusinessException("COACH_NOT_APPROVED","Availability coach does not have an active coach role");}
 public record PreferenceCommand(short sequenceNo,Instant startAt,Instant endAt,UUID preferredVenueId,String note){}
 public record CreateCommand(String lessonType,String scheduleType,String billingMode,String skillLevel,short participantCount,short guestParticipantCount,Short minimumParticipants,Short maximumParticipants,short requestedSessionCount,UUID preferredCoachProfileId,UUID selectedAvailabilityProposalId,List<PreferenceCommand> sessionPreferences,String notes){}
}
