package com.pickleball.booking.lessonrequest.api;

import com.pickleball.booking.identity.application.AuthenticatedPrincipal; import com.pickleball.booking.lessonrequest.application.LessonRequestService; import com.pickleball.booking.lessonrequest.application.LessonRequestService.*; import com.pickleball.booking.lessonrequest.infrastructure.*; import com.pickleball.booking.shared.api.ApiResponse;
import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.Instant; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1")
public class LessonRequestController {
 private final LessonRequestService service; public LessonRequestController(LessonRequestService service){this.service=service;} private AuthenticatedPrincipal p(Authentication a){return (AuthenticatedPrincipal)a.getPrincipal();} private <T> ApiResponse<T> ok(T data,HttpServletRequest r){return ApiResponse.of(data,(String)r.getAttribute("requestId"));}
 @PostMapping("/lesson-requests") @ResponseStatus(HttpStatus.CREATED) public ApiResponse<LessonView> create(Authentication a,@Valid @RequestBody CreateRequest r,HttpServletRequest h){return ok(view(service.create(p(a),command(r))),h);}
 @PatchMapping("/lesson-requests/{id}/selected-availability") public ApiResponse<LessonView> updateSelection(Authentication a,@PathVariable UUID id,@RequestBody SelectionRequest r,HttpServletRequest h){return ok(view(service.updateSelection(p(a),id,r.selectedAvailabilityProposalId())),h);}
 @PostMapping("/lesson-requests/{id}/submission") public ApiResponse<LessonView> submit(Authentication a,@PathVariable UUID id,@RequestHeader("Idempotency-Key") String idempotencyKey,HttpServletRequest h){return ok(view(service.submit(p(a),id,idempotencyKey)),h);}
 @PostMapping("/lesson-requests/{id}/review") public ApiResponse<LessonView> review(Authentication a,@PathVariable UUID id,@Valid @RequestBody ReviewRequest r,HttpServletRequest h){return ok(view(service.review(p(a),id,"APPROVE".equals(r.decision()),r.reviewNote())),h);}
 @GetMapping("/lesson-requests/mine") public ApiResponse<List<LessonView>> mine(Authentication a,HttpServletRequest h){return ok(service.mine(p(a)).stream().map(this::view).toList(),h);}
 @GetMapping("/lesson-requests") public ApiResponse<List<LessonView>> reviewList(Authentication a,@RequestParam UUID organizationId,HttpServletRequest h){return ok(service.forReview(p(a),organizationId).stream().map(this::view).toList(),h);}
 @GetMapping("/lesson-requests/{id}") public ApiResponse<LessonDetailView> detail(Authentication a,@PathVariable UUID id,HttpServletRequest h){var r=service.detail(p(a),id);return ok(new LessonDetailView(view(r),service.preferences(id).stream().map(this::preference).toList()),h);}
 private CreateCommand command(CreateRequest r){return new CreateCommand(r.lessonType(),r.scheduleType(),r.billingMode(),r.skillLevel(),r.participantCount(),r.guestParticipantCount(),r.minimumParticipants(),r.maximumParticipants(),r.requestedSessionCount(),r.preferredCoachProfileId(),r.selectedAvailabilityProposalId(),r.sessionPreferences().stream().map(x->new PreferenceCommand(x.sequenceNo(),x.startAt(),x.endAt(),x.preferredVenueId(),x.note())).toList(),r.notes());}
 private LessonView view(LessonRequestEntity e){return new LessonView(e.getId(),e.getRequesterUserId(),e.getPreferredCoachProfileId(),e.getSelectedAvailabilityProposalId(),e.getLessonType(),e.getScheduleType(),e.getBillingMode(),e.getSkillLevel(),e.getParticipantCount(),e.getGuestParticipantCount(),e.getMinimumParticipants(),e.getMaximumParticipants(),e.getRequestedSessionCount(),e.getStatus().name(),e.getNotes(),e.getSubmittedAt(),e.getReviewedBy(),e.getReviewedAt(),e.getReviewNote());} private PreferenceView preference(LessonSessionPreferenceEntity e){return new PreferenceView(e.getSequenceNo(),e.getStartAt(),e.getEndAt(),e.getPreferredVenueId(),e.getNote());}
 public record CreateRequest(@Pattern(regexp="PRIVATE|GROUP") String lessonType,@Pattern(regexp="SINGLE|RECURRING") String scheduleType,@Pattern(regexp="FULL_COURSE|PER_SESSION") String billingMode,@Size(max=30) String skillLevel,@Positive short participantCount,@Min(0) short guestParticipantCount,Short minimumParticipants,Short maximumParticipants,@Positive short requestedSessionCount,UUID preferredCoachProfileId,UUID selectedAvailabilityProposalId,@NotEmpty List<@Valid PreferenceRequest> sessionPreferences,@Size(max=10000) String notes){} public record SelectionRequest(UUID selectedAvailabilityProposalId){} public record PreferenceRequest(@Positive short sequenceNo,@NotNull Instant startAt,@NotNull Instant endAt,UUID preferredVenueId,@Size(max=500) String note){} public record ReviewRequest(@Pattern(regexp="APPROVE|REJECT") String decision,@NotBlank @Size(max=5000) String reviewNote){} public record LessonView(UUID id,UUID requesterUserId,UUID preferredCoachProfileId,UUID selectedAvailabilityProposalId,String lessonType,String scheduleType,String billingMode,String skillLevel,short participantCount,short guestParticipantCount,Short minimumParticipants,Short maximumParticipants,short requestedSessionCount,String status,String notes,Instant submittedAt,UUID reviewedBy,Instant reviewedAt,String reviewNote){} public record PreferenceView(short sequenceNo,Instant startAt,Instant endAt,UUID preferredVenueId,String note){} public record LessonDetailView(LessonView lessonRequest,List<PreferenceView> sessionPreferences){}
}
